# SmartCache Configuration File
# Generated on 2025-08-14

# Default network for contract operations
# Options: arbitrum-sepolia, arbitrum-one, arbitrum-nova, localhost
network = "arbitrum-sepolia"

# Your wallet address that deployed the contracts, this is required for all operations
deployed_by = "0x98097E5D48Cb9192352b44585a0d92CbCCE99b03"

# Optional: Default contract address
# If specified, you can run 'smart-cache add' without providing an address
contract_address = "0x7607faa0d401d8bb739562d0883e7c21c9b34424"

# Optional: Default contract metadata
# name = "MyContract"
# description = "Contract description"
version = "1.0.0"

# CLI behavior settings
interactive = false

# Optional: Custom metadata (add any additional fields you need)
# [metadata]
# author = "Your Name"
# license = "MIT"
# tags = ["defi", "nft"]
